package configs

const (
	MysqlHost     = "FILFI_MYSQL_HOST"
	MysqlPort     = "FILFI_MYSQL_PORT"
	MysqlUsername = "FILFI_MYSQL_USERNAME"
	MysqlPassword = "FILFI_MYSQL_PASSWORD"
	MysqlDatabase = "FILFI_MYSQL_DB"

	RedisHost     = "FILFI_REDIS_HOST"
	RedisPort     = "FILFI_REDIS_PORT"
	RedisPassword = "FILFI_REDIS_PASSWORD"

	InfluxdbUrl   = "FILFI_INFLUXDB_URL"
	InfluxdbToken = "FILFI_INFLUXDB_TOKEN"
	InfluxdbOrg   = "FILFI_INFLUXDB_ORG"

	LogLevel = "FILFI_LOG_LEVEL"

	LotusUrl       = "FILFI_LOTUS_URL"
	LotusAuthToken = "FILFI_LOTUS_AUTH_TOKEN"

	GlifUrlV0     = "FILFI_GLIF_URL_V0"
	GlifUrlV1     = "FILFI_GLIF_URL_V1"
	GlifAuthToken = "FILFI_GLIF_AUTH_TOKEN"

	FildataUrl   = "FILFI_FILDATA_URL"
	FildataToken = "FILFI_FILDATA_AUTH_TOKEN"

	FileEvmHttpsUrl = "FILFI_FILFEVM_HTTPS_URL"
	FilEvmWsUrl     = "FILFI_FILFEVM_WS_URL"
	FilEvmToken     = "FILFI_FILFEVM_AUTH_TOKEN"
	FilEvmContract  = "FILFI_FILFEVM_FACTORY_CONTRACT"

	FilNetwork = "FILFI_FIL_NETWORK"

	AwsAccessKey    = "FILFI_AWS_ACCESS_KEY_ID"
	AwsSecretKey    = "FILFI_AWS_SECRET_ACCESS_KEY"
	AwsRegion       = "FILFI_AWS_DEFAULT_REGION"
	AwsStaticBucket = "FILFI_STATIC_RES_BUCKET"

	InternalMinerService = "INTERNAL_MINER_SERVICE"
	InternalMinerKey     = "INTERNAL_MINER_SERVICE_KEY"

	Private_Key = "PRIVATE_KEY"
)

/*
export FILFI_MYSQL_USERNAME=root
export FILFI_MYSQL_PASSWORD=root2root
export FILFI_MYSQL_HOST=10.100.244.100
export FILFI_MYSQL_PORT=3306
export FILFI_MYSQL_DB=letsfill-2k
export FILFI_REDIS_HOST=10.100.244.100
export FILFI_REDIS_PORT=6379
export FILFI_REDIS_PASSWORD=
export FILFI_LOG_LEVEL=info
export FILFI_LOTUS_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.XUHbXcSrxu4iKo3X1xy0b9prXu-xHT2t1JJy8u2Eu7w
export FILFI_LOTUS_URL=http://10.7.3.9:1234/rpc/v0
export FILFI_GLIF_URL_V0=http://10.62.70.3:1234/rpc/v1
export FILFI_GLIF_URL_V1=http://10.62.70.3:1234/rpc/v1
export FILFI_GLIF_AUTH_TOKEN=
export FILFI_FILDATA_URL=http://10.100.244.100:33004
export FILFI_FILDATA_AUTH_TOKEN=
export FILFI_FILFEVM_HTTPS_URL=http://10.62.70.3:1234/rpc/v1
export FILFI_FILFEVM_WS_URL=http://10.62.70.3:1234/rpc/v1
export FILFI_FILFEVM_AUTH_TOKEN=
export FILFI_FILFEVM_FACTORY_CONTRACT=0x390CB629D5057AB6F990471a725179FdfB64dEFD
export FILFI_FIL_NETWORK=testnet
export FILFI_AWS_ACCESS_KEY_ID=
export FILFI_AWS_SECRET_ACCESS_KEY=
export FILFI_AWS_DEFAULT_REGION=
export FILFI_STATIC_RES_BUCKET=
*/
